services:
  - type: web
    name: hyakunin-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server_ws:app --host 0.0.0.0 --port $PORT"
    envVars: []
